In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('../stress_survey.csv')
# Replace weird characters in entire dataframe
df = df.replace(r'[âÂ]', '-', regex=True)
df = df.replace(r'[^\x00-\x7F]+', '-', regex=True)
df.head()

,Gender,Year,Branch,CGPA,Sleep_Hours,Screen_Time,Exercise_Freq,Diet_Quality,Study_Hours,Stress_Factors,GAD_Nervous,GAD_Irritable,Coping_Method,Counsellor_Need,Overall_Stress,College_Support,Programme,College Type
0,Female,1st Yr,MSME,Above 9.0,6 - 8 hours,1 - 3 hours,1 - 2 times a week,Very poor (mostly junk/irregular),2 - 4 hours,"Attendance pressure, Career and placement anxi...",2,3,"Talking to friends or family, Listening to mus...",No,4,"Yes, very much",B.Tech,IIT
1,Male,2nd Yr,CSE / IT,6.0 - 7.0,6 - 8 hours,3 - 5 hours,Daily,Average,Less than 2 hours,"Exams and assignments, Career and placement an...",1,1,"Exercise or sports, Sleeping it off, Ignoring/...",No,7,Somewhat,B.Tech,IIT
2,Male,2nd Yr,DSAI,8.0 - 9.0,6 - 8 hours,More than 5 hours,3 - 4 times a week,Good,2 - 4 hours,"Exams and assignments, Attendance pressure, La...",3,3,"Listening to music / watching content, Exercis...","Yes, and I did seek help",9,Somewhat,B.Tech,IIT
3,Male,2nd Yr,CSE / IT,8.0 - 9.0,4 - 6 hours,1 - 3 hours,Daily,Very good (balanced meals),Less than 2 hours,"Exams and assignments, Peer comparison / compe...",3,3,"Talking to friends or family, Listening to mus...",No,9,Somewhat,B.Tech,IIT
4,Male,2nd Yr,CSE / IT,8.0 - 9.0,6 - 8 hours,3 - 5 hours,1 - 2 times a week,Average,Less than 2 hours,"Exams and assignments, Peer comparison / compe...",2,2,"Talking to friends or family, Exercise or spor...","Yes, but I did not seek help",8,Somewhat,B.Tech,IIT

In [3]:
print(df.columns)

Index(['Gender', 'Year', 'Branch', 'CGPA', 'Sleep_Hours', 'Screen_Time',
       'Exercise_Freq', 'Diet_Quality', 'Study_Hours', 'Stress_Factors',
       'GAD_Nervous', 'GAD_Irritable', 'Coping_Method', 'Counsellor_Need',
       'Overall_Stress', 'College_Support', 'Programme', 'College Type'],
      dtype='object')

In [4]:
df.describe()

       GAD_Nervous  GAD_Irritable  Overall_Stress
count   102.000000     102.000000      102.000000
mean      2.245098       2.186275        5.637255
std       0.999369       1.050510        2.702361
min       1.000000       1.000000        1.000000
25%       1.000000       1.000000        4.000000
50%       2.000000       2.000000        6.000000
75%       3.000000       3.000000        8.000000
max       4.000000       4.000000       10.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           102 non-null    object
 1   Year             102 non-null    object
 2   Branch           102 non-null    object
 3   CGPA             102 non-null    object
 4   Sleep_Hours      102 non-null    object
 5   Screen_Time      102 non-null    object
 6   Exercise_Freq    102 non-null    object
 7   Diet_Quality     102 non-null    object
 8   Study_Hours      102 non-null    object
 9   Stress_Factors   102 non-null    object
 10  GAD_Nervous      102 non-null    int64
 11  GAD_Irritable    102 non-null    int64
 12  Coping_Method    102 non-null    object
 13  Counsellor_Need  102 non-null    object
 14  Overall_Stress   102 non-null    int64
 15  College_Support  88 non-null     object
 16  Programme        102 non-null    object
 17  College Type     102 non-null    object
dtypes: int64(3), object(15)
memory usage: 14.5+ KB

In [6]:
df.columns

Index(['Gender', 'Year', 'Branch', 'CGPA', 'Sleep_Hours', 'Screen_Time',
       'Exercise_Freq', 'Diet_Quality', 'Study_Hours', 'Stress_Factors',
       'GAD_Nervous', 'GAD_Irritable', 'Coping_Method', 'Counsellor_Need',
       'Overall_Stress', 'College_Support', 'Programme', 'College Type'],
      dtype='object')

In [7]:
df.to_csv('cleaned_stress_survey.csv', index=False)